name: metalearn-navigator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - nodejs=18
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - sqlalchemy==2.0.23
    - aiosqlite==0.19.0
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - python-dotenv==1.0.0
    - httpx==0.25.2
    - openai==1.3.7
    - requests==2.31.0
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
